# Ce fichier permet de définir la manière dont doit être exécuté votre projet
# sur le serveur de production, ainsi que les différents services dont il
# besoin
#
# Pour mettre en place le déploiement continu sur votre projet :
# 1) Modifiez boilerplate par le nom de votre projet, ainsi que ebm-boilerplate 
#     dans le nom de l'image
# 2) Ajoutez les services dont dépend votre projet comme ici pour mongo (en commentaire)
version: "3"
services:
  boilerplate: # replacer par le nom de votre projet (ex: oklm)
    image: ebm1718travis/ebm-boilerplate:latest # indiquez ici le nom de l'image de votre projet, ex :
                                                # ebm1718travis/oklm:latest
    networks:
      - boilerplate # replacer par le nom de votre projet (ex: oklm)
      - ebm-filrouge # ne pas modifier cette ligne pour rendre le service accessible pour les autres projets
  # mongodb:
  #   image: mongo
  #   networks:
  #     - boilerplate # pertmet au service mongo de communiquer avec votre projet, mais il ne doit pas être
  #                   # accessible pour les autres équipes
networks:
  boilerplate: # replacer par le nom de votre projet (ex: oklm)
  ebm-filrouge:
    external: true 